# Lets start with EDA

In [3]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
cardiac_failure = pd.read_csv("data/cardiac_failure_processed.csv")

In [5]:
cardio_base = pd.read_csv("data/cardio_base.csv")

In [6]:
heart_processed = pd.read_csv("data/heart_processed.csv")

In [7]:
heart_processed.head(5)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True

In [8]:
heart_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   RestingBP          918 non-null    int64
 2   Cholesterol        918 non-null    int64
 3   FastingBS          918 non-null    int64
 4   MaxHR              918 non-null    int64
 5   Oldpeak            918 non-null    float64
 6   HeartDisease       918 non-null    int64
 7   Sex_M              918 non-null    bool
 8   ChestPainType_ATA  918 non-null    bool
 9   ChestPainType_NAP  918 non-null    bool
 10  ChestPainType_TA   918 non-null    bool
 11  RestingECG_Normal  918 non-null    bool
 12  RestingECG_ST      918 non-null    bool
 13  ExerciseAngina_Y   918 non-null    bool
 14  ST_Slope_Flat      918 non-null    bool
 15  ST_Slope_Up        918 non-null    bool
dtypes: bool(9), float64(1), int64(6)
memory usage: 58.4 KB

In [9]:
cardio_base.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 1 columns):
 #   Column                                                                             Non-Null Count  Dtype
---  ------                                                                             --------------  -----
 0   id;age;gender;height;weight;ap_hi;ap_lo;cholesterol;gluc;smoke;alco;active;cardio  70000 non-null  str
dtypes: str(1)
memory usage: 547.0 KB

In [10]:
cardio_base = pd.read_csv("data/cardio_base.csv" , delimiter= ";")

In [11]:
cardio_base.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [12]:
cardiac_failure.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   70000 non-null  int64
 1   id           70000 non-null  int64
 2   age          70000 non-null  float64
 3   gender       70000 non-null  int64
 4   height       70000 non-null  int64
 5   weight       70000 non-null  float64
 6   ap_hi        70000 non-null  int64
 7   ap_lo        70000 non-null  int64
 8   cholesterol  70000 non-null  int64
 9   gluc         70000 non-null  int64
 10  smoke        70000 non-null  int64
 11  alco         70000 non-null  int64
 12  active       70000 non-null  int64
 13  cardio       70000 non-null  int64
dtypes: float64(2), int64(12)
memory usage: 7.5 MB

In [13]:
cardiac_failure.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,70000.0,34999.500000,20207.403759,0.0,17499.75000,34999.500000,52499.250000,69999.0
id,70000.0,49972.419900,28851.302323,0.0,25006.75000,50001.500000,74889.250000,99999.0
age,70000.0,0.671379,0.191038,0.0,0.53163,0.689508,0.815254,1.0
gender,70000.0,1.349571,0.476838,1.0,1.00000,1.000000,2.000000,2.0
height,70000.0,164.359229,8.210126,55.0,159.00000,165.000000,170.000000,250.0
weight,70000.0,74.205690,14.395757,10.0,65.00000,72.000000,82.000000,200.0
ap_hi,70000.0,128.817286,154.011419,-150.0,120.00000,120.000000,140.000000,16020.0
ap_lo,70000.0,96.630414,188.472530,-70.0,80.00000,80.000000,90.000000,11000.0
cholesterol,70000.0,1.366871,0.680250,1.0,1.00000,1.000000,2.000000,3.0
gluc,70000.0,1.226457,0.572270,1.0,1.00000,1.000000,1.000000,3.0
smoke,70000.0,0.088129,0.283484,0.0,0.00000,0.000000,0.000000,1.0
alco,70000.0,0.053771,0.225568,0.0,0.00000,0.000000,0.000000,1.0
active,70000.0,0.803729,0.397179,0.0,1.00000,1.000000,1.000000,1.0
cardio,70000.0,0.499700,0.500003,0.0,0.00000,0.000000,1.000000,1.0

In [14]:
cardio_base

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [15]:
cardiac_failure = cardiac_failure.drop(columns= cardiac_failure[["Unnamed: 0"]])

In [16]:
cardiac_failure.compare(cardio_base)

            age
           self  other
0      0.588076  18393
1      0.730159  20228
2      0.624003  18857
3      0.528455  17623
4      0.516918  17474
...         ...    ...
69995  0.653659  19240
69996  0.913899  22601
69997  0.640186  19066
69998  0.900736  22431
69999  0.754317  20540

[70000 rows x 2 columns]

In [17]:
heart_processed.head(5)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,True,True,False,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,True,True,False,False,False,True,False,False,True
3,48,138,214,0,108,1.5,1,False,False,False,False,True,False,True,True,False
4,54,150,195,0,122,0.0,0,True,False,True,False,True,False,False,False,True

In [18]:
#Okay note , cardiac base and failure are identical datasets,
#one with normalised age. 

#heart processesed is a small set with 1000 samples (validation probably)
#Labels don't match , something else

#Lets do EDA 
#im only using cardiac failure for baseline.

In [19]:
#cardiac failure
px.histogram(title= "Age vs cardio" , data_frame= cardiac_failure , x = 'age',
y= 'cardio' , color='cholesterol' )

In [20]:
px.histogram(title= "Age vs cardio" , data_frame= cardiac_failure , x = 'age',
y= 'cardio' , color='smoke')

In [21]:
px.histogram(data_frame= cardiac_failure , x = "age" , y= "cardio" , color= "active")

In [22]:
#We notice a pattern , people across all age group having a CVD 
#have more people who have cholesterol 2 , smoke and are not active.

#Lets see the correlation map

In [24]:
px.histogram(cardiac_failure , x="gender" , color="cardio")

In [25]:
#Data for both genders are almost balanced ,
#  one gender seems more frequtly present. 

#Lets build models to start predicting.
#  Lets try several models : logistic regression , SVM , Naive Bayes ,
# Gradient boosting and random forests.

In [26]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC , SVR
from sklearn.naive_bayes import GaussianNB 
from xgboost import XGBRegressor , XGBClassifier
from sklearn.ensemble import RandomForestClassifier

#These will be our base models , then we will try to build a custom
#model 

import random
from scipy.stats import randint , uniform
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV

In [27]:
#Let's process the data into numerical columns and prepare them 
# and split the data 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [28]:
train_data =  cardiac_failure.copy().drop(columns=[ "cardio" , "id"])

target = cardiac_failure["cardio"]

In [29]:
train_data.columns

Index(['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol',
       'gluc', 'smoke', 'alco', 'active'],
      dtype='str')

In [30]:
num_cols = ['age' , 'height' , 'weight' , 'ap_hi' ,
            'ap_lo']

cat_cols = ['gender','gluc','smoke' , 'alco' , 'active']

In [31]:
x_train , x_test , y_train , y_test = train_test_split(train_data , target , test_size= 0.2)

In [32]:
x_train[cat_cols].info()

<class 'pandas.DataFrame'>
Index: 56000 entries, 10237 to 38075
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   gender  56000 non-null  int64
 1   gluc    56000 non-null  int64
 2   smoke   56000 non-null  int64
 3   alco    56000 non-null  int64
 4   active  56000 non-null  int64
dtypes: int64(5)
memory usage: 2.6 MB

In [33]:
scaler = MinMaxScaler().fit(x_train[num_cols])
encoder = OneHotEncoder(sparse_output= False , handle_unknown= 'ignore').fit((x_train[cat_cols]).astype(str))

In [34]:
encoded_cols = list(encoder.get_feature_names_out(cat_cols))
encoded_cols

['gender_1',
 'gender_2',
 'gluc_1',
 'gluc_2',
 'gluc_3',
 'smoke_0',
 'smoke_1',
 'alco_0',
 'alco_1',
 'active_0',
 'active_1']

In [35]:
x_train[num_cols] = scaler.transform(x_train[num_cols])
x_test[num_cols] = scaler.transform(x_test[num_cols])

x_train[encoded_cols] = encoder.transform(x_train[cat_cols].astype(str))
x_test[encoded_cols] = encoder.transform(x_test[cat_cols].astype(str))

In [36]:
X_train = x_train[num_cols + encoded_cols]
X_test = x_test[num_cols + encoded_cols]

In [37]:
X_train

,age,height,weight,ap_hi,ap_lo,gender_1,gender_2,gluc_1,gluc_2,gluc_3,smoke_0,smoke_1,alco_0,alco_1,active_0,active_1
10237,0.807142,0.548718,0.394737,0.019054,0.013550,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
53403,0.847596,0.589744,0.289474,0.019054,0.013550,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
12037,0.853820,0.538462,0.226316,0.019054,0.013550,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
17976,0.752217,0.528205,0.278947,0.019054,0.014453,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
30094,0.673954,0.564103,0.278947,0.022583,0.014453,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24677,0.494943,0.605128,0.352632,0.020466,0.014453,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
3588,0.923215,0.558974,0.278947,0.019760,0.014453,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
65360,0.973471,0.610256,0.426316,0.019054,0.013550,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
17206,0.623230,0.600000,0.347368,0.019054,0.013550,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
38075,0.871013,0.528205,0.347368,0.020466,0.014453,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [38]:
def train_model(model , input , targets , test , test_preds):
    model.fit(input , targets)

    y_pred = model.predict(input)


    acc = accuracy_score(targets , y_pred)


    print(f" Accuracy = {acc}")

In [39]:
#Lets start with XGBoost model. 

xgb_model = XGBClassifier(n_jobs=-1, random_state=42, n_estimators=1000, 
                     learning_rate=0.02, max_depth=8, subsample=0.9, 
                     colsample_bytree=0.7)

In [40]:
train_model(xgb_model , X_train , y_train , X_test , y_test)

 Accuracy = 0.7773214285714286

In [41]:
preds = xgb_model.predict(X_test)

pred_prob = xgb_model.predict_proba(X_test)

acc = accuracy_score(y_test , preds )

acc

0.7281428571428571

In [42]:
preds

array([1, 1, 1, ..., 0, 0, 1], shape=(14000,))

In [43]:
pred_prob

array([[0.25197703, 0.748023  ],
       [0.13566339, 0.8643366 ],
       [0.18718833, 0.8128117 ],
       ...,
       [0.7413312 , 0.25866875],
       [0.5947515 , 0.40524855],
       [0.27051026, 0.72948974]], shape=(14000, 2), dtype=float32)

In [44]:
#Lets create the different models 

logistic = LogisticRegression()
rf_model = RandomForestClassifier(max_depth= 10,
 max_features = 'log2',
 min_samples_leaf = 4,
 min_samples_split = 19,
 n_estimators = 829)

In [45]:
train_model(logistic , X_train , y_train , X_test , y_test)

 Accuracy = 0.6322857142857143

In [46]:
train_model(rf_model , X_train , y_train , X_test , y_test)

 Accuracy = 0.7411964285714285

In [47]:
pred = rf_model.predict(X_test)

acc = accuracy_score(y_test , pred)

acc

0.7322857142857143

In [48]:
param_distributions = {
    "n_estimators": randint(100, 1000),
    "max_depth": randint(5, 50),
    "min_samples_split": randint(2, 20),
    "min_samples_leaf": randint(1, 10),
    "max_features": ["sqrt", "log2", None]
}

In [49]:
#lets try to find the best parameters for the RF and GBM models as they
# perform better. 

rand = RandomizedSearchCV(estimator= RandomForestClassifier(random_state=42),param_distributions=param_distributions, # note the name
n_iter=50, # number of sampled configs
cv=5,
scoring='accuracy',
n_jobs=-1,
random_state=42,
verbose=1
)

In [50]:
# rand.fit(X_train , y_train)

In [51]:
# rand.best_params_

#even with random search we ony got a marginally better model

In [52]:
#Now lets try a GBM 
param_distributions = {
"n_estimators": randint(100, 1000),
"learning_rate": uniform(0.01, 0.2),
"max_depth": randint(2, 6),
"min_samples_split": randint(2, 20),
"min_samples_leaf": randint(1, 10),
"subsample": uniform(0.6, 0.4)}

In [53]:
# rand_gbm = RandomizedSearchCV( estimator= XGBClassifier() ,param_distributions=param_distributions,
#     n_iter=50,
#     cv=5,
#     scoring="neg_root_mean_squared_error",
#     n_jobs=-1,
#     random_state=42,
#      verbose=1 )

In [54]:
# rand_gbm.fit(X_train , y_train)

In [55]:
# rand_gbm.best_params_

In [56]:
gbm_model = XGBClassifier(max_depth = 5 , min_sample_leaf = 7 , 
                          min_sample_split = 2 , n_estimators = 555 ,
                          subsample = 0.9 , learning_rate = 0.06)

In [57]:
train_model(gbm_model , X_train , y_train , X_test , y_test)

/Users/swapneelpremchand/CVD/.venv/lib/python3.13/site-packages/xgboost/training.py:200: UserWarning:

[17:26:46] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:782:
Parameters: { "min_sample_leaf", "min_sample_split" } are not used.

 Accuracy = 0.7498035714285715

In [58]:
preds = gbm_model.predict(X_test)

acc = accuracy_score(y_test , preds)

acc

0.7306428571428571

In [76]:
#Even with best parameters we just get around 73% accuracy. 

#Lets build a torch model. 
# We will have a linear model with BCE loss.

import torch
from torch.optim import AdamW
import torch.nn as nn

In [69]:
class CardioClassifier(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(num_features, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        return self.net(x).squeeze(1)

In [70]:
X_train.columns #16 cols

Index(['age', 'height', 'weight', 'ap_hi', 'ap_lo', 'gender_1', 'gender_2',
       'gluc_1', 'gluc_2', 'gluc_3', 'smoke_0', 'smoke_1', 'alco_0', 'alco_1',
       'active_0', 'active_1'],
      dtype='str')

In [71]:
CardioV0 = CardioClassifier(num_features= 16)

In [72]:
CardioV0

CardioClassifier(
  (net): Sequential(
    (0): Linear(in_features=16, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [77]:
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import Adam

# prefer mps/cuda if available
device = torch.device("mps" if torch.backends.mps.is_available() else ("cuda" if torch.cuda.is_available() else "cpu"))

# create tensors (no device kw for from_numpy) and move to device
X_train_t = torch.from_numpy(X_train.to_numpy(dtype="float32", copy=False)).to(device)
y_train_t = torch.from_numpy(y_train.to_numpy(dtype="float32", copy=False)).to(device)
X_test_t  = torch.from_numpy(X_test.to_numpy(dtype="float32", copy=False)).to(device)
y_test_t  = torch.from_numpy(y_test.to_numpy(dtype="float32", copy=False)).to(device)

batch_size = 256
# use pinned memory / workers only when using CUDA for speed
pin_memory = True if device.type == "cuda" else False
num_workers = 2 if device.type == "cuda" else 0

train_ds = TensorDataset(X_train_t, y_train_t)
test_ds  = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=pin_memory)
test_loader  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=pin_memory)

# move model to device 
CardioV0 = CardioClassifier(num_features=X_train.shape[1]).to(device)
loss_fn = nn.BCEWithLogitsLoss()
optimizer = AdamW(CardioV0.parameters(), lr=1e-3)

In [78]:
#Training loop

from tqdm.auto import tqdm

epochs = 100



for epoch in tqdm(range(epochs)):
    CardioV0.train()

    for xb , yb in train_loader : 
        xb = xb.to(device)
        yb = yb.to(device)

        train_loss = 0
        train_correct = 0
        train_total = 0

        logits = CardioV0(xb)

        loss = loss_fn(logits , yb)

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()

        train_loss += loss.item() * xb.size(0)
        preds = (torch.sigmoid(logits) >= 0.5).float()
        train_correct += (preds == yb).sum().item()
        train_total += xb.size(0)


    train_loss = train_loss / train_total
    train_acc = train_correct / train_total

    # --- eval ---
    CardioV0.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0
    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            yb = yb.to(device)
            logits = CardioV0(xb)
            loss = loss_fn(logits, yb)

            val_loss += loss.item() * xb.size(0)
            preds = (torch.sigmoid(logits) >= 0.5).float()
            val_correct += (preds == yb).sum().item()
            val_total += xb.size(0)

    val_loss = val_loss / val_total
    val_acc = val_correct / val_total

    print(f"Epoch {epoch+1}/{epochs} — train_loss: {train_loss:.4f} train_acc: {train_acc:.4f} | val_loss: {val_loss:.4f} val_acc: {val_acc:.4f}")

  0%|          | 0/100 [00:00<?, ?it/s]

Epoch 1/100 — train_loss: 0.6823 train_acc: 0.5521 | val_loss: 0.6734 val_acc: 0.5971
Epoch 2/100 — train_loss: 0.6329 train_acc: 0.6667 | val_loss: 0.6595 val_acc: 0.6129
Epoch 3/100 — train_loss: 0.6427 train_acc: 0.5938 | val_loss: 0.6525 val_acc: 0.6156
Epoch 4/100 — train_loss: 0.6545 train_acc: 0.6042 | val_loss: 0.6498 val_acc: 0.6171
Epoch 5/100 — train_loss: 0.6886 train_acc: 0.5521 | val_loss: 0.6478 val_acc: 0.6212
Epoch 6/100 — train_loss: 0.6595 train_acc: 0.5938 | val_loss: 0.6466 val_acc: 0.6219
Epoch 7/100 — train_loss: 0.6456 train_acc: 0.6667 | val_loss: 0.6459 val_acc: 0.6239
Epoch 8/100 — train_loss: 0.6594 train_acc: 0.6146 | val_loss: 0.6448 val_acc: 0.6261
Epoch 9/100 — train_loss: 0.6326 train_acc: 0.6562 | val_loss: 0.6447 val_acc: 0.6270
Epoch 10/100 — train_loss: 0.6586 train_acc: 0.6406 | val_loss: 0.6444 val_acc: 0.6266
Epoch 11/100 — train_loss: 0.6458 train_acc: 0.6667 | val_loss: 0.6439 val_acc: 0.6266
Epoch 12/100 — train_loss: 0.6403 train_acc: 0.6927 | val_loss: 0.6439 val_acc: 0.6284
Epoch 13/100 — train_loss: 0.6697 train_acc: 0.6146 | val_loss: 0.6432 val_acc: 0.6299
Epoch 14/100 — train_loss: 0.6228 train_acc: 0.6875 | val_loss: 0.6429 val_acc: 0.6296
Epoch 15/100 — train_loss: 0.6241 train_acc: 0.6719 | val_loss: 0.6422 val_acc: 0.6309
Epoch 16/100 — train_loss: 0.6751 train_acc: 0.5938 | val_loss: 0.6419 val_acc: 0.6294
Epoch 17/100 — train_loss: 0.6614 train_acc: 0.5833 | val_loss: 0.6417 val_acc: 0.6295
Epoch 18/100 — train_loss: 0.6576 train_acc: 0.6302 | val_loss: 0.6427 val_acc: 0.6303
Epoch 19/100 — train_loss: 0.6572 train_acc: 0.6042 | val_loss: 0.6413 val_acc: 0.6307
Epoch 20/100 — train_loss: 0.6473 train_acc: 0.6250 | val_loss: 0.6416 val_acc: 0.6322
Epoch 21/100 — train_loss: 0.6397 train_acc: 0.6562 | val_loss: 0.6410 val_acc: 0.6304
Epoch 22/100 — train_loss: 0.6326 train_acc: 0.6406 | val_loss: 0.6405 val_acc: 0.6326
Epoch 23/100 — train_loss: 0.6389 train_acc: 0.6146 | val_loss: 0.6403 val_acc: 0.6340
Epoch 24/100 — train_loss: 0.6189 train_acc: 0.6615 | val_loss: 0.6402 val_acc: 0.6326
Epoch 25/100 — train_loss: 0.6061 train_acc: 0.6979 | val_loss: 0.6402 val_acc: 0.6334
Epoch 26/100 — train_loss: 0.6146 train_acc: 0.6719 | val_loss: 0.6397 val_acc: 0.6329
Epoch 27/100 — train_loss: 0.6311 train_acc: 0.6458 | val_loss: 0.6397 val_acc: 0.6333
Epoch 28/100 — train_loss: 0.6314 train_acc: 0.6354 | val_loss: 0.6392 val_acc: 0.6332
Epoch 29/100 — train_loss: 0.6207 train_acc: 0.6510 | val_loss: 0.6394 val_acc: 0.6336
Epoch 30/100 — train_loss: 0.6112 train_acc: 0.6927 | val_loss: 0.6404 val_acc: 0.6342
Epoch 31/100 — train_loss: 0.6305 train_acc: 0.6302 | val_loss: 0.6389 val_acc: 0.6334
Epoch 32/100 — train_loss: 0.6617 train_acc: 0.6198 | val_loss: 0.6412 val_acc: 0.6289
Epoch 33/100 — train_loss: 0.6640 train_acc: 0.5833 | val_loss: 0.6384 val_acc: 0.6328
Epoch 34/100 — train_loss: 0.6503 train_acc: 0.6250 | val_loss: 0.6382 val_acc: 0.6345
Epoch 35/100 — train_loss: 0.6248 train_acc: 0.6042 | val_loss: 0.6379 val_acc: 0.6351
Epoch 36/100 — train_loss: 0.6092 train_acc: 0.6771 | val_loss: 0.6388 val_acc: 0.6367
Epoch 37/100 — train_loss: 0.6474 train_acc: 0.6458 | val_loss: 0.6379 val_acc: 0.6356
Epoch 38/100 — train_loss: 0.6972 train_acc: 0.5677 | val_loss: 0.6386 val_acc: 0.6344
Epoch 39/100 — train_loss: 0.6824 train_acc: 0.6094 | val_loss: 0.6379 val_acc: 0.6349
Epoch 40/100 — train_loss: 0.6504 train_acc: 0.6406 | val_loss: 0.6371 val_acc: 0.6352
Epoch 41/100 — train_loss: 0.6003 train_acc: 0.7031 | val_loss: 0.6380 val_acc: 0.6363
Epoch 42/100 — train_loss: 0.7188 train_acc: 0.5990 | val_loss: 0.6369 val_acc: 0.6352
Epoch 43/100 — train_loss: 0.6633 train_acc: 0.6198 | val_loss: 0.6370 val_acc: 0.6372
Epoch 44/100 — train_loss: 0.6293 train_acc: 0.6615 | val_loss: 0.6364 val_acc: 0.6369
Epoch 45/100 — train_loss: 0.6270 train_acc: 0.6458 | val_loss: 0.6372 val_acc: 0.6344
Epoch 46/100 — train_loss: 0.6289 train_acc: 0.6406 | val_loss: 0.6368 val_acc: 0.6348
Epoch 47/100 — train_loss: 0.6175 train_acc: 0.6562 | val_loss: 0.6366 val_acc: 0.6359
Epoch 48/100 — train_loss: 0.6443 train_acc: 0.6094 | val_loss: 0.6357 val_acc: 0.6381
Epoch 49/100 — train_loss: 0.6456 train_acc: 0.6146 | val_loss: 0.6357 val_acc: 0.6364
Epoch 50/100 — train_loss: 0.6912 train_acc: 0.5521 | val_loss: 0.6359 val_acc: 0.6359
Epoch 51/100 — train_loss: 0.6654 train_acc: 0.5729 | val_loss: 0.6353 val_acc: 0.6364
Epoch 52/100 — train_loss: 0.6324 train_acc: 0.6771 | val_loss: 0.6378 val_acc: 0.6374
Epoch 53/100 — train_loss: 0.6534 train_acc: 0.6406 | val_loss: 0.6348 val_acc: 0.6384
Epoch 54/100 — train_loss: 0.6134 train_acc: 0.6667 | val_loss: 0.6347 val_acc: 0.6367
Epoch 55/100 — train_loss: 0.6610 train_acc: 0.5990 | val_loss: 0.6345 val_acc: 0.6394
Epoch 56/100 — train_loss: 0.6225 train_acc: 0.6198 | val_loss: 0.6364 val_acc: 0.6336
Epoch 57/100 — train_loss: 0.6463 train_acc: 0.6302 | val_loss: 0.6339 val_acc: 0.6400
Epoch 58/100 — train_loss: 0.5994 train_acc: 0.6927 | val_loss: 0.6338 val_acc: 0.6389
Epoch 59/100 — train_loss: 0.6566 train_acc: 0.6354 | val_loss: 0.6352 val_acc: 0.6356
Epoch 60/100 — train_loss: 0.6052 train_acc: 0.6562 | val_loss: 0.6334 val_acc: 0.6401
Epoch 61/100 — train_loss: 0.6253 train_acc: 0.6198 | val_loss: 0.6333 val_acc: 0.6409
Epoch 62/100 — train_loss: 0.6760 train_acc: 0.6250 | val_loss: 0.6335 val_acc: 0.6394
Epoch 63/100 — train_loss: 0.6598 train_acc: 0.6042 | val_loss: 0.6335 val_acc: 0.6400
Epoch 64/100 — train_loss: 0.6544 train_acc: 0.6458 | val_loss: 0.6325 val_acc: 0.6405
Epoch 65/100 — train_loss: 0.6160 train_acc: 0.6354 | val_loss: 0.6351 val_acc: 0.6432
Epoch 66/100 — train_loss: 0.6204 train_acc: 0.6406 | val_loss: 0.6324 val_acc: 0.6421
Epoch 67/100 — train_loss: 0.6664 train_acc: 0.5990 | val_loss: 0.6321 val_acc: 0.6444
Epoch 68/100 — train_loss: 0.6610 train_acc: 0.6094 | val_loss: 0.6316 val_acc: 0.6421
Epoch 69/100 — train_loss: 0.6162 train_acc: 0.6562 | val_loss: 0.6319 val_acc: 0.6395
Epoch 70/100 — train_loss: 0.6005 train_acc: 0.6615 | val_loss: 0.6317 val_acc: 0.6404
Epoch 71/100 — train_loss: 0.6020 train_acc: 0.6719 | val_loss: 0.6312 val_acc: 0.6431
Epoch 72/100 — train_loss: 0.6206 train_acc: 0.6667 | val_loss: 0.6317 val_acc: 0.6456
Epoch 73/100 — train_loss: 0.6399 train_acc: 0.5990 | val_loss: 0.6298 val_acc: 0.6443
Epoch 74/100 — train_loss: 0.7407 train_acc: 0.6719 | val_loss: 0.6301 val_acc: 0.6454
Epoch 75/100 — train_loss: 0.6623 train_acc: 0.5938 | val_loss: 0.6295 val_acc: 0.6431
Epoch 76/100 — train_loss: 0.6149 train_acc: 0.6667 | val_loss: 0.6309 val_acc: 0.6410
Epoch 77/100 — train_loss: 0.6191 train_acc: 0.6615 | val_loss: 0.6291 val_acc: 0.6447
Epoch 78/100 — train_loss: 0.6216 train_acc: 0.6562 | val_loss: 0.6298 val_acc: 0.6491
Epoch 79/100 — train_loss: 0.6500 train_acc: 0.6094 | val_loss: 0.6293 val_acc: 0.6418
Epoch 80/100 — train_loss: 0.6240 train_acc: 0.6302 | val_loss: 0.6285 val_acc: 0.6468
Epoch 81/100 — train_loss: 0.6192 train_acc: 0.6406 | val_loss: 0.6292 val_acc: 0.6431
Epoch 82/100 — train_loss: 0.6583 train_acc: 0.6510 | val_loss: 0.6277 val_acc: 0.6446
Epoch 83/100 — train_loss: 0.6267 train_acc: 0.6406 | val_loss: 0.6276 val_acc: 0.6459
Epoch 84/100 — train_loss: 0.6234 train_acc: 0.6562 | val_loss: 0.6277 val_acc: 0.6445
Epoch 85/100 — train_loss: 0.6442 train_acc: 0.6510 | val_loss: 0.6262 val_acc: 0.6506
Epoch 86/100 — train_loss: 0.6096 train_acc: 0.6771 | val_loss: 0.6259 val_acc: 0.6516
Epoch 87/100 — train_loss: 0.6037 train_acc: 0.6875 | val_loss: 0.6263 val_acc: 0.6471
Epoch 88/100 — train_loss: 0.6688 train_acc: 0.6094 | val_loss: 0.6258 val_acc: 0.6503
Epoch 89/100 — train_loss: 0.6360 train_acc: 0.6354 | val_loss: 0.6281 val_acc: 0.6427
Epoch 90/100 — train_loss: 0.6567 train_acc: 0.6354 | val_loss: 0.6251 val_acc: 0.6554
Epoch 91/100 — train_loss: 0.6531 train_acc: 0.6094 | val_loss: 0.6243 val_acc: 0.6537
Epoch 92/100 — train_loss: 0.6684 train_acc: 0.5573 | val_loss: 0.6239 val_acc: 0.6509
Epoch 93/100 — train_loss: 0.5988 train_acc: 0.6771 | val_loss: 0.6248 val_acc: 0.6536
Epoch 94/100 — train_loss: 0.6358 train_acc: 0.6458 | val_loss: 0.6240 val_acc: 0.6503
Epoch 95/100 — train_loss: 0.5778 train_acc: 0.6979 | val_loss: 0.6312 val_acc: 0.6469
Epoch 96/100 — train_loss: 0.5917 train_acc: 0.6927 | val_loss: 0.6232 val_acc: 0.6568
Epoch 97/100 — train_loss: 0.6443 train_acc: 0.6354 | val_loss: 0.6220 val_acc: 0.6586
Epoch 98/100 — train_loss: 0.6122 train_acc: 0.6771 | val_loss: 0.6215 val_acc: 0.6586
Epoch 99/100 — train_loss: 0.6189 train_acc: 0.6667 | val_loss: 0.6216 val_acc: 0.6525
Epoch 100/100 — train_loss: 0.6036 train_acc: 0.7292 | val_loss: 0.6251 val_acc: 0.6521

# Summary — current model performance 

## XGBoost (XGBClassifier)

Trained with tuned hyperparameters (many estimators, low LR, depth ~5–8).
Best performance ≈ 73% accuracy on test set.
Strength: highest reported accuracy so far.


## Random Forest

Trained with constrained tree settings (max_depth=10, many estimators).
Accuracy was computed in notebook to be around 72%.  Expected to be in the same ballpark as XGBoost (± a few points).
Good baseline and feature-importance insight.


## Logistic Regression / SVM / GaussianNB

Created and fit; individual accuracy values lower than RF and GBM.(62%)

Logistic is the simple baseline — likely worse than the tree ensembles on this dataset.


## PyTorch MLP (CardioV0)

Simple MLP (16 → 32 → 1), BCEWithLogitsLoss, AdamW optimizer, DataLoader pipeline implemented.
Training loop present , gives test accuracy of 65% only marginally better than the Logistic model. (low as expected)

In [79]:
from scripts import save_models


#lets save our models. 

save_models.save_sklearn_model(logistic , "LogisticRegression.mdl")
save_models.save_sklearn_model(rf_model , "RandomForest.mdl")
save_models.save_sklearn_model(gbm_model , "GradientBoosting.mdl")
save_models.save_torch_model(CardioV0 , "MLPmodel" , True)

PosixPath('/Users/swapneelpremchand/CVD/models/MLPmodel_state_dict.pth')